export const projectData = [
  {
    nom: "Oria 2 brochure",
    desc: "Programmation sur Gatsby d'une brochure papier en mode virtuelle pour les condominiums Oria II. Mode administratif fonctionnant sur le cms Prismic",
    designer: "Bivouac Studio",
    stack: ["Gatsby", "Prismic", "Framer-Motion"],
    img: "/oria2-b.png",
    url: "https://www.oria2brochure.com/",
    urlName: "oria2brochure.com/",
  },

  {
    nom: "Tableaux de bord dynamique",
    desc: "Création d'un tableau de bord dynamique pour service de traiteur avec zone administrative conceptualisée avec React-big-calendar, Material-ui et utilisant Airtable comme base de données. Consultation sur tableau numérique et application web mobile",
    designer: "Sébastien Francisque",
    stack: [
      "NextJS",
      "Firebase",
      "Airtable",
      "PusherJS",
      "Mui",
      "Reac Big Calendar",
    ],
    img: "/signage1.png",
    imgArr: ["/signage.png", "/signage-m.png", "/commande.png"],
    url: "",
    github: "https://github.com/rustyblue100/tableau-dynamique",
  },
  {
    nom: "Free Run Artists",
    desc: `Conception de site Wordpress sur mesure utilisant
    Underscores avec zone administrative utilisant Advanced
    Custom Fields.`,
    designer: "Sébastien Francisque",
    stack: ["Wordpress", "Underscores", "Advanced Custom Fields", "SASS"],
    img: "/freerun.png",
    url: "https://freerunartists.com/",
    urlName: "freerunartists.com/",
    github: "https://github.com/rustyblue100/freerunartists",
  },
  {
    nom: "Générateur de signatures de courriels",
    desc: "Programmation en MERN stack d'un générateur de signatures de courriels",
    designer: "Bivouac Studio",
    stack: ["MongoDB", "ExpressJS", "ReactJS", "NodeJS", "Cloudinary"],
    img: "/smartmockups_l1o8uqia.jpeg",
    imgArr: [
      "/email-list.png",
      "/ajouter.png",
      "/email-search.png",
      "/email-single.png",
    ],
    url: "https://app-signatures.herokuapp.com/",
    urlName: "app-signatures.herokuapp.com/",
    github: "https://github.com/rustyblue100/app-signatures",
    demo: { user: "transfer@folospot", password: 12345 },
  },
  {
    nom: "Papagroove",
    desc: "Conception site web avec Gatsby est administrée sur le cms Sanity",
    designer: "Sébastien Francisque",
    stack: ["Gatsby", "Sanity"],
    img: "/papagroove.png",
    url: "https://papagroove.ca/",
    urlName: "papagroove.ca/",
  },

  {
    nom: "Grande Rencontre des Arts Médiatiques en Gaspésie",
    desc: 'Programmation personnalisée du site des "Grande Rencontre des Arts Médiatiques en Gaspésie" sur Wordpress.',
    designer: "Rui Silveira",
    stack: ["Wordpress", "Advanced Custom Fields", "Generatepress"],
    img: "/gaspesie.png",
    url: "https://perceides.ca/etatsgenerauxartsmediatiquesgaspesie/",
    urlName: "perceides.ca/etatsgenerauxartsmediatiquesgaspesie/",
  },
  {
    nom: "farwestleather.com",
    desc: "Conception de site Wordpress sur mesure utilisant le thème de base Understrap et WooCommerce pour l'affichage des produits",
    designer: "Sébastien Francisque",
    stack: ["Wordpress", "Understrap", " Bootstrap", "Woocommerce"],
    img: "/farwest.png",
    url: "https://farwestleather.com",
    urlName: "farwestleather.com/",
  },
];
