export const projectData = [
  {
    nom: "Oria 2 brochure",
    desc: "lalal",
    designer: "Bivouac Studio",
    stack: ["Gatsby", "Prismic"],
    img: "/oria2-b.jpeg",
    url: "https://www.oria2brochure.com/",
    urlName: "oria2brochure.com/",
  },

  {
    nom: "Tableaux de bord dynamique",
    desc: "lalal",
    designer: "Sébastien Francisque",
    stack: [
      "Next.js",
      "Airtable",
      "Firebase",
      "Pusher.js",
      "Mui",
      "Reac Big Calendar",
    ],
    img: "/signage1.png",
    imgArr: ["/signage1.png", "/signage-m.jpeg", "/commande.png"],
    url: "",
  },
  {
    nom: "Free Run Artists",
    desc: "lalal",
    designer: "Sébastien Francisque",
    stack: ["word"],
    img: "/freerun.jpeg",
    url: "https://freerunartists.com/",
    urlName: "freerunartists.com/",
    github: "https://github.com/rustyblue100/freerunartists",
  },
  {
    nom: "Générateur de signatures de courriels",
    desc: "lalal",
    designer: "Bivouac Studio",
    stack: ["word"],
    img: "/smartmockups_l1o8uqia.jpeg",
    imgArr: ["/email-list.png", "/email-search.png", "/email-single.png"],
    url: "",
    github: "https://github.com/rustyblue100/app-signatures",
  },
  {
    nom: "Papagroove",
    desc: "lalal",
    designer: "Sébastien Francisque",
    stack: ["Gatsby", "Sanity"],
    img: "/papagroove.jpeg",
    url: "https://papagroove.ca/",
    urlName: "papagroove.ca/",
  },

  {
    nom: "Grande Rencontre des Arts Médiatiques en Gaspésie",
    desc: "lalal",
    designer: "Rui Silveira",
    stack: ["Wordpress", "ACF", "Generatepress"],
    img: "/gaspesie.jpeg",
    url: "https://perceides.ca/etatsgenerauxartsmediatiquesgaspesie/",
    urlName: "perceides.ca/etatsgenerauxartsmediatiquesgaspesie/",
  },
  {
    nom: "farwestleather.com",
    desc: "Conception de site Wordpress sur mesure utilisant le thème de base Understrap et WooCommerce pour l'affichage des produits",
    designer: "Sébastien Francisque",
    stack: ["Wordpress", "Understrap", " Bootstrap", " ACF", "Woocommerce"],
    img: "/farwest.jpeg",
    url: "https://farwestleather.com",
    urlName: "farwestleather.com/",
  },
];
